### ISSUE TITLE
직사각형 넓이 구하기 문제 오타

### ISSUE THREAD

**Issue by sewonkimm** [Team-ZeroHouse/js-algorithm-training-webapp#20]
안녕하세요. 
js로 알고리즘 연습해보려고 검색해보다가 발견하게 되어 잘 트레이닝하고 있습니다 ^^

직사각형 넓이 구하기 문제에서 오타를 발견하여 이슈 등록합니다.
```
입력
밑변과 넓이가 공백을 기준으로 한줄에 출력된다.
```

```
입력
밑변과 높이가 공백을 기준으로 한줄에 출력된다.
```
로 수정되어야 할 것 같네요!

알고리즘 문제 추가되기를 기다리겠습니다~

**Comment by TsooranKim** [comment]
#21 수정하였습니다.
